sudo: required

language: python

services:
  - docker

stages:
  - build_ui
  - build_server

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

jobs:
  include:
    - stage: build_ui
      script: sh ./scripts/build_ui.sh
    - stage: build_server
      script: sh ./scripts/build_server.sh
