---
version: '2'

services:
    mix-answer-server:
        build: 
            context: server
            dockerfile: Dockerfile
        container_name: mix-answer-server
        network_mode: bridge
        volumes:
            - ./server:/home/server
        ports:
            - "5000:5000"
        links:
            - mix-answer-postgres:db
            - mix-answer-redis:redis

    mix-answer-postgres:
        image: postgres:9.4
        container_name: mix-answer-postgres
        network_mode: bridge
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=mixuser
            - POSTGRES_PASSWORD=mixuser
            - POSTGRES_DB=mixanswer

    mix-answer-redis:
        image: redis:3.2
        container_name: mix-answer-redis
        network_mode: bridge
        volumes:
          - redis-data:/data

    mix-answer-ui:
        build: 
            context: ui
            dockerfile: Dockerfile
        container_name: mix-answer-ui
        network_mode: bridge
        ports:
            - "8081:8081"
        volumes:
            - ./ui/app:/home/webapp/app
            - ./ui/scripts:/home/webapp/scripts

volumes:
    postgres-data:
    redis-data:
